(require "core")
(require "base.scm")
(require "objects.scm")
(require "tools.scm")

(declare *err* &native)


;; Set FN to VALUE and return RETVAL
(define (_fswap fn value retval)
  &native
  (_fset fn value)
  retval)


(define `(catchErrorIn expr)
  (define `(saveError msg)
    (_set "*err*" (or msg "-")))

  (_fswap "_error" (_fswap "_error" saveError _error) expr)
  *err*)


;; Return `.PROP` if GOAL ends in `).PROP` and PROP does not contain `)`.
;; Nil otherwise.
;;
(define `(isProp goal)
  (if (findstring ")." goal)
      (filter-out ". %)" (subst ")" ") " goal))))


;; Return the class portion of instance ID.  Return nil if ID has no "(", no
;; ")", or begins with "(".
;;
(define `(idc id)
  (filter-out "|% %)" (subst "(" " |" (filter "%)" id))))


;; Return inheritance chain (a list of all the classes that will be
;; searched, in order) for CHP (zero or more classes).
;;
(define (_chain chp ?seen)
  &native
  (if chp
      (_chain (_chp+ chp) (._. seen (word 1 chp)))
      (strip seen)))


;; Return 1 if some definition of P is present for ID
;;
(define (_hasProperty p id)
  &native
  (if (native-strip (foreach (scope (_chain id))
                      (defined? (.. scope "." p))))
      1))


(define (_fmtList ids)
  &native
  (if (word 1 ids)
      (subst " " "\n   " (.. " " (native-strip ids)))
      "none"))


(define (_helpDeps id)
  &native
  (define `needs (get "needs" id))
  (.. "Direct dependencies: " (_fmtList needs) "\n\n"
      "Indirect dependencies: " (_fmtList (filter-out needs (_rollup needs)))))


(define (_helpOnInvalidClass goal)
  &native
  (.. "\"" goal "\" looks like an instance with an invalid class name;\n"
      "`$" (idc goal) ".inherit` is not defined.  Perhaps a typo?\n"))


(define (_helpOnInstance id)
  &native
  (.. id " is an instance.\n\n"
      "{out} = " (get "out" id) "\n\n"
      (if (_hasProperty "command" id)
          (.. "Command: " (_qvn (_escapeR (get "command" id))))
          (.. "{rule} = " (_qvn (get "rule" id))))
      "\n"
      "\n"
      (_helpDeps id) "\n"))


(define (_helpOnIndirect goal)
  &native
  (.. "\"" goal "\" is an indirection on the following "
      (if (findstring "*" (_ivar goal))
          (.. "wildcard:\n\n   " (_ivar goal))
          (.. "variable:\n\n   " (_describeVar (_ivar goal))))
      "\n\n"
      "It expands to the following targets: " (_fmtList (_expand goal)) "\n"))


(define (_helpOnAlias goal)
  &native
  (.. "\"" goal "\" is an alias for " (_isAlias goal) ".\n"
      "\n"
      "It is defined by:\n"
      "   " (_describeVar goal) "\n\n"
      (_helpDeps (_isAlias goal)) "\n"
      "\n"
      "It generates the following rule: " (_qvn (get "rule" (_isAlias goal)))))


(define (_describeProp chp prop)
  &native
  (define `(recur)
    (_describeProp (_chp+ chp) prop))

  (define `var
    (.. (word 1 chp) "." prop))

  (define `has-inherit
    (and (recursive? var)
         (findstring "{inherit}" (native-value var))))

  (if chp
      (if (undefined? var)
          (recur)
          (.. (_describeVar var "   ") "\n"
              (if has-inherit
                  (.. "\n...wherein {inherit} references:\n\n" (recur)))))
      "   <missing definition!>\n"))


;; Show definitions
(define `(propertyInfo p id)
  (.. ""
      "" id " inherits from: " (_chain (idc id)) "\n"
      "\n"
      "{" p "} " (if (_hasProperty p id)
                     (.. "is defined by:\n\n"
                         (_describeProp id p))
                     "is not defined!")))


(define `(propertyValue p id)
  (..
   (if (catchErrorIn (get p id))
       (.. "Its evaluation results in an error:\n" *err*)
       (.. "Its value is: " (_qv (get p id))))
   "\n\n"))


(define (_helpOnProperty goal)
  &native
  (foreach (p (patsubst ".%" "%" (isProp goal)))
    (foreach (id (patsubst (.. "%." p) "%" goal))
      (_info (propertyInfo p id))  ;; output before trying evaluation
      (propertyValue p id))))


(define (_helpOnOther goal)
  &native
  (.. "Target " goal " is not generated by Minion.  It may be a source\n"
      "file or a target defined by a rule in the Makefile."))


;; True when ID -- which must be an instance -- has an invalid class name.
;;
(define `(isClassInvalid id)
  (undefined? (.. (idc id) ".inherit")))


(define (_helpType goal)
  &native
  (if (isProp goal)
      "Property"
      (if (_isInstance goal)
          (if (isClassInvalid goal)
              "InvalidClass"
              "Instance")
          (if (_isIndirect goal)
              "Indirect"
              (if (_isAlias goal) "Alias"
                  "Other")))))


(define (_help! goal)
  &native
  (print (native-call (.. "_helpOn" (_helpType goal)) goal)))
