(require "core")

(require "base.scm")
(require "objects.scm")
(require "tools.scm")


(define (_fmtList ids)
  &native
  (if (word 1 ids)
      (subst " " "\n   " (.. " " (native-strip ids)))
      "none"))


(define (_helpDeps id)
  &native
  (define `needs (get "needs" id))
  (.. "Direct dependencies: " (_fmtList needs) "\n\n"
      "Indirect dependencies: " (_fmtList (filter-out needs (_rollup needs)))))


(define (_isProp goal)
  &native
  (filter ").%" (lastword (subst ")" " )" goal))))


(define (_helpInvalidClass goal)
  &native
  (.. "\"" goal "\" looks like an instance with an invalid class name;\n"
      "`$" (_idC goal) ".inherit` is not defined.  Perhaps a typo?\n"))


;; escape for expansion (TODO: factor with lazy & recipe)
;;
(define (_renc str)
  &native
  (subst "\x1b" "$" (subst "$" "$$" str)))


(define (_helpInstance id)
  &native
  (.. id " is an instance.\n\n"
      "{out} = " (get "out" id) "\n\n"
      (if (_hasProperty "command" id)
          (.. "Command: " (_qvn (_renc (get "command" id))))
          (.. "{rule} = " (_qvn (get "rule" id))))
      "\n"
      "\n"
      (_helpDeps id) "\n"))


(define (_helpIndirect goal)
  &native
  (.. "\"" goal "\" is an indirection on the following "
      (if (findstring "*" (_ivar goal))
          (.. "wildcard:\n\n   " (_ivar goal))
          (.. "variable:\n\n   " (_describeVar (_ivar goal))))
      "\n\n"
      "It expands to the following targets: " (_fmtList (_expand goal)) "\n"))


(define (_helpAlias goal)
  &native
  (.. "\"" goal "\" is an alias for " (_isAlias goal) ".\n"
      "\n"
      "It is defined by:\n"
      "   " (_describeVar goal) "\n\n"
      (_helpDeps (_isAlias goal)) "\n"
      "\n"
      "It generates the following rule: " (_qvn (get "rule" (_isAlias goal)))))


;; # $1 = C(A).P; $2 = description;  $(id) = C(A); $p = P
(define (_helpPropertyInfo goal desc id p)
  &native
  (.. ""
      "" id " inherits from: " (_chain (_idC id)) "\n"
      "\n"
      "{" p "} " (if (if desc "" goal) ;; TODO
                     "is not defined!"
                     (.. "is defined by:\n"
                         "\n"
                         desc "\n"
                         "\n"
                         "Its value is: " (_qv (get p id))))
      "\n"
      "\n"))


(define (_helpProperty goal)
  &native
  (foreach (p (or (lastword (subst ")." ") " goal))
                  (error (.. "Empty property name in " goal))))
    (foreach (id (patsubst (.. "%)." p) "%)" goal))
      (_helpPropertyInfo goal (_describeProp id p) id p))))


(define (_helpOther goal)
  &native
  (.. "Target " goal " is not generated by Minion.  It may be a source\n"
      "file or a target defined by a rule in the Makefile."))


(define (_goalType goal)
  &native
  (if (_isProp goal)
      "Property"
      (if (_isInstance goal)
          (if (_isClassInvalid goal)
              "InvalidClass"
              "Instance")
          (if (_isIndirect goal)
              "Indirect"
              (if (_isAlias goal) "Alias"
                  "Other")))))


(define (_help! goal)
  &native
  (print (native-call (.. "_help" (_goalType goal)) goal)))
