# Miscellaneous make functions for test makefiles

# $(call _range,MIN,MAX) : Return a list of integers from MIN to MAX, inclusive.
#
# [generated by range.scm]
_rxn = $(if $(word $2,$1),$1,$(call _rxn,$(foreach ;,0 1 2 3 4 5 6 7 8 9,$(addprefix $;,$1)),$2))
_range = $(if $(subst 0,,$2),$(wordlist $1,$2,$(subst $(\s)0, ,$(subst $(\s)00, ,$(subst $(\s)0000, , $(call _rxn,0 1 2 3 4 5 6 7 8 9,$2) $2)))))


# $(call _words,LENGTH,WORD) : return LENGTH repetitions of WORD
#
_words = $(if $(word $1,$2),$(wordlist 1,$1,$2),$(call _words,$1,$2 $2))


# $(call _slowdown,X,FUNC) : repeat FUNC X times each time it is called.  This
#    effectively slows down execution of FUNC by a factor of X to allow more
#    accurate benchmarking with `time make`.   NOTE:  FUNC may not be recursive.
#

# $(call _getXFunc,NREPS) -> name of XFunc (a function that evals $0_ NREPS times)
_getXFunc = $(if $(filter u%,$(flavor _X$1)),$(eval _X$1 = $(_xfuncBody)))_X$1
_xfuncBody = $(subst x ,$$(if $$($$0_),),$(wordlist 2,999999,$(call _words,$1,x)) )$$($$0_)

_slowdown = \
  $(if $(filter u%,$(origin $2)),$(error slowdown: '$2' is not defined))\
  $(eval $2_ = $(value $2))\
  $(eval $2 = $$($(_getXFunc)))


# $(_autoSlowdown) : slow down functions named in `slowdownX<NUM>` variables.
#
_autoSlowdown = \
  $(foreach v,$(filter slowdownX%,$(.VARIABLES)),\
     $(call _slowdown,$(subst slowdownX,,$v),$($v)))


# $(call _!!, MESSAGE) : output base command suffix to display warning on failure
#
_!! = || ( echo 'FAILURE: $(_self): $1'; false )
